trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Windows Build
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NuGetToolInstaller@0

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.300'

  - task: NuGetCommand@2
    displayName: 'Nuget Restore'
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    inputs: 
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'BinDrop' 
    
  #- task: NuGetCommand@2
  #  displayName: 'Nuget Pack'
  #  inputs:
  #    command: pack
  #    packagesToPack: 'nuspec/**.nuspec'

  #- task: NuGetCommand@2
  #  displayName: 'Nuget Push'
  #  inputs:
  #    command: push
  #    nuGetFeedType: external
  #    publishFeedCredentials: 'Nuget.org SimpleProcessFramework'
  #    versioningScheme: byEnvVar
  #    versionEnvVar: Version
  #    packagesToPush: nuspec/**.nupkg

- job: Windows Test
  dependsOn: Windows Build
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'BinDrop'
      downloadPath: '$(System.ArtifactsDirectory)' 